const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

const endpoints = [
  {
    method: "POST",
    path: "/api/paraphrase",
    description: "Paraphrase text with adjustable intensity",
    body: { text: "The quick brown fox jumps over the lazy dog.", intensity: 3 },
  },
  {
    method: "POST",
    path: "/api/grammar-check",
    description: "Check grammar, spelling, and punctuation",
    body: { text: "This are a sentence with bad grammar.", language: "en-US" },
  },
  {
    method: "POST",
    path: "/api/summarize",
    description: "Summarize text in paragraph or bullet mode",
    body: {
      text: "Paste a long article here…",
      mode: "paragraph",
      max_length: 150,
    },
  },
  {
    method: "POST",
    path: "/api/translate",
    description: "Translate text between 100+ languages",
    body: { text: "Hello, world!", source_language: "en", target_language: "fr" },
  },
  {
    method: "POST",
    path: "/api/humanize",
    description: "Humanize AI-generated text",
    body: { text: "The utilization of artificial intelligence…" },
  },
];

export default function ApiDocsPage() {
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold mb-1">Developer API</h1>
      <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">
        All features are available via a RESTful API. Interactive docs are auto-generated by FastAPI.
      </p>

      <div className="flex gap-3 mb-8">
        <a
          href={`${API_URL}/docs`}
          target="_blank"
          rel="noopener noreferrer"
          className="px-4 py-2 rounded-lg bg-brand-600 hover:bg-brand-700 text-white text-sm font-medium transition-colors"
        >
          Open Swagger UI ↗
        </a>
        <a
          href={`${API_URL}/redoc`}
          target="_blank"
          rel="noopener noreferrer"
          className="px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-700 text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
        >
          Open ReDoc ↗
        </a>
      </div>

      <div className="space-y-4">
        {endpoints.map((ep) => (
          <div
            key={ep.path}
            className="rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden"
          >
            <div className="flex items-center gap-3 px-4 py-3 bg-gray-50 dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700">
              <span className="px-2 py-0.5 rounded text-xs font-bold bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300">
                {ep.method}
              </span>
              <code className="text-sm font-mono text-gray-800 dark:text-gray-200">{ep.path}</code>
            </div>
            <div className="px-4 py-3">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">{ep.description}</p>
              <details>
                <summary className="text-xs text-brand-600 dark:text-brand-400 cursor-pointer hover:underline">
                  Example request body
                </summary>
                <pre className="mt-2 p-3 bg-gray-900 dark:bg-black text-green-400 text-xs rounded-lg overflow-x-auto">
                  {JSON.stringify(ep.body, null, 2)}
                </pre>
              </details>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 p-4 bg-brand-50 dark:bg-brand-950 rounded-xl border border-brand-200 dark:border-brand-800 text-sm">
        <strong className="text-brand-700 dark:text-brand-300">Base URL:</strong>{" "}
        <code className="font-mono">{API_URL}</code>
        <br />
        <span className="text-gray-600 dark:text-gray-400 text-xs">
          All endpoints accept JSON and return JSON. No authentication required.
        </span>
      </div>
    </div>
  );
}
